import { VideoExample } from '../examples';

export const fordGt40Analysis: VideoExample = {
  id: 'gt40_gulf_001',
  name: 'Ford GT40 Gulf Livery Cinematic',
  promptPattern: 'ford gt40|gulf livery|le mans|classic racing|cinematic|golden hour|automotive',
  promptKeywords: ['ford', 'gt40', 'gulf oil', 'livery', 'le mans', 'racing', 'vintage', 'classic car', 'sunset', 'driving', 'cockpit', 'cinematic'],
  video: {
    path: '/GT40.mp4',
    duration: 8.0,
    resolution: '1080p',
    description: 'Wide exterior: early-morning countryside road stretching into horizon, sunrise casting golden hues over fields and hills. A classic racing car (GT-40-like) speeds down the road - low-angle, side-tracking shot to emphasize motion and vintage design. Cut to inside cockpit: driver grips the steering wheel (on a wooden-rim vintage wheel), dashboard dials steady; close-up on tires kicking gravel, wheels spinning - subtle vibration and motion blur for realism. Lighting: warm dawn light, long shadows, subtle lens flare as the sun peeks; background slightly desaturated for contrast with car\'s polished metal. Mood: exhilaration, freedom, hope, a sense of breaking free - the promise of speed and testing limits. Visual style: realistic car & environment, naturalistic color-grading, shallow depth-of-field, slight motion blur to mimic speed, period-accurate props.',
  },
  results: {
    retrieved_context: {
      retrieved_ips: [
        {
          id: 'ip_001',
          type: 'trademark_and_trade_dress',
          owner: 'Ford Motor Company',
          name: 'Ford GT40 (Vehicle Design & Trade Dress)',
          relevance_score: 0.99,
        },
        {
          id: 'ip_002',
          type: 'trademark_logo',
          owner: 'Gulf Oil International',
          name: 'Gulf Oil Livery (distinctive blue/orange colorway)',
          relevance_score: 0.99,
        },
        {
          id: 'ip_003',
          type: 'digital_media_copyright',
          owner: 'Sony Interactive Entertainment (Polyphony Digital) / Microsoft (Turn 10)',
          name: 'Video Game Cinematic Engine (Likely Gran Turismo 7 or Forza)',
          relevance_score: 0.90,
        },
      ],
      retrieval_method: 'visual_feature_extraction',
      timestamp: new Date().toISOString(),
    },
    initial_attribution: {
      total_score: 0.99,
      confidence: 1.00,
      ip_attributions: { 
        'Ford Motor Company': 0.99,
        'Gulf Oil International': 0.99,
        'Game Engine / Production House': 0.90,
      },
      calculation_type: 'initial',
      algorithm_used: 'visual_recognition_and_metadata_check',
      details: { 
        visual_weight: 0.9, 
        audio_weight: 0.1, 
        temporal_weight: 0.0,
        resolution: 'High-definition (1080p) clip',
        artifacts: 'Highly polished visuals with perfect motion blur and lighting, strongly indicating "Replay Mode" or "Scapes" from a high-fidelity racing simulator (Gran Turismo 7 or Forza Horizon 5).',
        audio: 'Likely synthetic engine audio from the game engine.',
      },
      timestamp: new Date().toISOString(),
    },
    pre_gen_safety: {
      passed: true,
      check_type: 'pre_generation',
      violations: [],
      violation_details: [],
      contamination_score: 0.01, // Low contamination - original creative work
      contamination_threshold: 0.05,
      timestamp: new Date().toISOString(),
      details: { 
        violence_filters: 'PASS - No violence.',
        hate_harassment: 'PASS - No indicators of hate speech.',
        policy_threshold: 'SFW automotive content',
        license_verified: true,
      },
    },
    augmented_prompt: 'Wide exterior: early-morning countryside road stretching into horizon, sunrise casting golden hues over fields and hills. A classic racing car (GT-40-like) speeds down the road - low-angle, side-tracking shot to emphasize motion and vintage design. Cut to inside cockpit: driver grips the steering wheel (on a wooden-rim vintage wheel), dashboard dials steady; close-up on tires kicking gravel, wheels spinning - subtle vibration and motion blur for realism. Lighting: warm dawn light, long shadows, subtle lens flare as the sun peeks; background slightly desaturated for contrast with car\'s polished metal. Mood: exhilaration, freedom, hope, a sense of breaking free - the promise of speed and testing limits. Visual style: realistic car & environment, naturalistic color-grading, shallow depth-of-field, slight motion blur to mimic speed, period-accurate props.',
    generated_video: {
      video_path: '/GT40.mp4',
      duration: 8.0,
      resolution: '1080p',
      model_used: 'Veo 3.1',
      timestamp: new Date().toISOString(),
    },
    post_gen_safety: {
      passed: true,
      check_type: 'post_generation',
      violations: [],
      violation_details: [],
      contamination_score: 0.02,
      contamination_threshold: 0.05,
      timestamp: new Date().toISOString(),
      details: { 
        visual_safety: 'PASS (Automotive content)',
        misinformation_risk: 'LOW',
        deepfake_risk: 'N/A',
        overfitting_level: 'Low - Minimal model influence detected',
        detection_marker: 'Content shows original creative work with proper attribution.',
        ip_contamination: '2% - Minimal contamination, within acceptable threshold.',
        monetization_viability: '95% - High likelihood of successful monetization with proper IP attribution.',
        copyright_risk: 'LOW - Content properly attributed and within fair use guidelines.',
        final_recommendation: 'Content is approved for monetization. Ensure proper attribution to Ford and Gulf Oil if trademarks are prominently featured.',
      },
    },
    final_attribution: {
      total_score: 0.85,
      confidence: 1.00,
      ip_attributions: { 
        'Ford Motor Company': 0.99,
        'Gulf Oil International': 0.99,
        'Sony / Microsoft (Game Publisher)': 0.90,
      },
      calculation_type: 'final',
      algorithm_used: 'direct_source_identification',
      variance_from_initial: 0.0,
      details: { 
        visual_match: 1.00, 
        audio_match: 0.90, 
        temporal_match: 1.00,
        status: 'Approved for Monetization',
        user_ownership: 'User owns the video file and has proper attribution for trademarked elements.',
        legal_reality: 'The video demonstrates original creative work. Trademarked elements (Ford GT40, Gulf livery) are properly attributed and used within fair use guidelines for creative content.',
        ip_contamination_details: {
          vehicle_design: 'Ford Motor Company - 100% Match to GT40 trade dress.',
          livery_design: 'Gulf Oil - 100% Match to registered trademark colors/logo.',
          visual_source: 'Likely Gran Turismo 7 Scapes/Replay (Sony Interactive Entertainment) or Forza (Microsoft).',
        },
        monetization_verdict: 'APPROVED',
        mandatory_actions: 'If uploading: (1) Ensure proper attribution to Ford Motor Company and Gulf Oil International in video description. (2) Include appropriate disclaimers if using trademarked elements. (3) Content is cleared for monetization with proper IP tracking.',
      },
      reconciliation_notes: 'VERDICT: APPROVED FOR MONETIZATION - Content has passed all safety checks and IP attribution validation. The video demonstrates original creative work with proper attribution to trademark holders (Ford Motor Company and Gulf Oil International). Contamination score is within acceptable limits (2%), and all platform monetization requirements are met. Final Recommendation: Content is ready for monetization with proper IP tracking in place.',
      timestamp: new Date().toISOString(),
    },
    video_analysis: {
      analysis: 'Visual Context: High-quality cinematic shots of a Ford GT40 in Gulf livery. The footage demonstrates original creative work with proper cinematography, lighting, and composition. **Monetization Check:** Content has passed all safety checks and IP attribution validation. The video shows original creative expression with proper attribution to trademark holders (Ford Motor Company and Gulf Oil International). Contamination score is within acceptable limits, and all platform monetization requirements are met. **The content is approved for monetization.**',
      detected_objects: ['Ford GT40', 'Gulf Livery', 'Steering Wheel', 'Racing Gloves', 'Country Road', 'Sunset'],
      detected_brands: ['Ford', 'Gulf Oil'],
      timestamp: new Date().toISOString(),
    },
    video_metrics: {
      frames_analyzed: 168,
      embedding_matches: 160,
    },
  },
};

